GRANT SELECT ON STAFF_B TO branchdb_B;
GRANT INSERT ON STAFF_B TO branchdb_B;

GRANT SELECT ON STAFF_A TO Branchdb_A;
GRANT INSERT ON STAFF_A TO branchdb_A;
GRANT SELECT ON DEPARTMENT_A TO Branchdb_A;
GRANT SELECT ON SYSTEM.DEPARTMENT_A TO Branchdb_A;
SELECT table_name FROM user_tables WHERE table_name = 'PAYROLL';
GRANT SELECT ON PAYROLL TO SYSTEM;
GRANT INSERT ON PAYROLL_LOG TO branchdb_B;

GRANT SELECT ON v$lock TO BRANCHDB_A;
GRANT SELECT ON v$session TO BRANCHDB_A;
-----------
ALTER SESSION SET CONTAINER = XEPDB1;

ALTER USER BRANCHDB_A IDENTIFIED BY "12345";
ALTER USER BRANCHDB_A ACCOUNT UNLOCK;
GRANT CONNECT TO BRANCHDB_A;
GRANT SELECT ON SYSTEM.STAFF_A TO BRANCHDB_A;

SELECT
  s.sid,
  s.serial#,
  s.username,
  s.status,
  s.program
FROM
  v$session s
WHERE
  s.username IS NOT NULL;
  ALTER SYSTEM KILL SESSION '139,25780
  ALTER SYSTEM KILL SESSION '139,39018' IMMEDIATE;

GRANT ALTER SYSTEM TO Branchdb_A;




